[package]
name = "poseidon"
version = "0.2.0"
authors = ["kilic <kiliconu@itu.edu.tr>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
subtle = { version = "2.3", default-features = false }
ff = { version = "0.13", features = ["derive"] }

[features]
default = []
